-- ============================================
-- Script SQL Complet pour la Base de Données
-- Plateforme de Questions-Réponses pour Étudiants
-- ============================================
-- Ce script crée toutes les tables, colonnes, politiques RLS et fonctions
-- nécessaires pour dupliquer la base de données en entier.
--
-- ATTENTION : Ce script doit être exécuté sur une base de données vide
-- ou après avoir supprimé toutes les tables existantes.
--
-- Prérequis :
-- 1. Projet Supabase créé
-- 2. Bucket de stockage 'avatars' créé en mode public via l'interface Supabase
--
-- Ordre d'exécution :
-- 1. Exécuter ce script dans l'éditeur SQL de Supabase
-- 2. Le bucket 'avatars' doit être créé manuellement via Storage → Create bucket
-- ============================================


-- ============================================
-- SECTION 1 : CRÉATION DES TABLES
-- ============================================

-- -----------------------------------------------
-- Table: profiles
-- Description: Profils utilisateurs publics
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  username text UNIQUE,
  avatar_url text,
  is_admin boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- -----------------------------------------------
-- Table: questions
-- Description: Questions posées par les utilisateurs
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL, -- Contenu Markdown
  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  is_answered boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamptz DEFAULT now(),
  last_editor_id uuid REFERENCES profiles(id),
  tags text[]
);

-- -----------------------------------------------
-- Table: comments
-- Description: Commentaires sur les questions
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id bigint REFERENCES questions(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamptz DEFAULT now(),
  last_editor_id uuid REFERENCES profiles(id)
);


-- ============================================
-- SECTION 2: CRÉATION DES INDEX
-- ============================================

-- Index pour améliorer les performances des requêtes fréquentes
CREATE INDEX IF NOT EXISTS idx_questions_user_id ON questions(user_id);
CREATE INDEX IF NOT EXISTS idx_questions_created_at ON questions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_questions_is_answered ON questions(is_answered);
CREATE INDEX IF NOT EXISTS idx_comments_question_id ON comments(question_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at);


-- ============================================
-- SECTION 3: ROW LEVEL SECURITY (RLS)
-- ============================================

-- Activer RLS sur toutes les tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------
-- Politiques RLS pour la table: profiles
-- -----------------------------------------------

-- Tout le monde peut voir tous les profils
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON profiles;
CREATE POLICY "Public profiles are viewable by everyone." 
  ON profiles FOR SELECT 
  USING (true);

-- Les utilisateurs peuvent créer leur propre profil
DROP POLICY IF EXISTS "Users can insert their own profile." ON profiles;
CREATE POLICY "Users can insert their own profile." 
  ON profiles FOR INSERT 
  WITH CHECK (auth.uid() = id);

-- Les utilisateurs peuvent modifier leur propre profil
DROP POLICY IF EXISTS "Users can update own profile." ON profiles;
CREATE POLICY "Users can update own profile." 
  ON profiles FOR UPDATE 
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- -----------------------------------------------
-- Politiques RLS pour la table: questions
-- -----------------------------------------------

-- Tout le monde peut voir toutes les questions
DROP POLICY IF EXISTS "Questions are viewable by everyone." ON questions;
CREATE POLICY "Questions are viewable by everyone." 
  ON questions FOR SELECT 
  USING (true);

-- Les utilisateurs authentifiés peuvent créer des questions
DROP POLICY IF EXISTS "Authenticated users can create questions." ON questions;
CREATE POLICY "Authenticated users can create questions." 
  ON questions FOR INSERT 
  WITH CHECK (auth.role() = 'authenticated');

-- Le propriétaire d'une question peut la modifier
DROP POLICY IF EXISTS "Question owner can update question." ON questions;
CREATE POLICY "Question owner can update question." 
  ON questions FOR UPDATE 
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Les administrateurs peuvent modifier n'importe quelle question
DROP POLICY IF EXISTS "Admins can update any question." ON questions;
CREATE POLICY "Admins can update any question." 
  ON questions FOR UPDATE 
  USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  );

-- Les utilisateurs peuvent supprimer leurs propres questions
DROP POLICY IF EXISTS "Users can delete own questions." ON questions;
CREATE POLICY "Users can delete own questions." 
  ON questions FOR DELETE 
  USING (auth.uid() = user_id);

-- Les administrateurs peuvent supprimer n'importe quelle question
DROP POLICY IF EXISTS "Admins can delete any question." ON questions;
CREATE POLICY "Admins can delete any question." 
  ON questions FOR DELETE 
  USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  );

-- -----------------------------------------------
-- Politiques RLS pour la table: comments
-- -----------------------------------------------

-- Tout le monde peut voir tous les commentaires
DROP POLICY IF EXISTS "Comments are viewable by everyone." ON comments;
CREATE POLICY "Comments are viewable by everyone." 
  ON comments FOR SELECT 
  USING (true);

-- Les utilisateurs authentifiés peuvent créer des commentaires
DROP POLICY IF EXISTS "Authenticated users can create comments." ON comments;
CREATE POLICY "Authenticated users can create comments." 
  ON comments FOR INSERT 
  WITH CHECK (auth.role() = 'authenticated');

-- Les utilisateurs peuvent modifier leurs propres commentaires
DROP POLICY IF EXISTS "Users can update own comments." ON comments;
CREATE POLICY "Users can update own comments." 
  ON comments FOR UPDATE 
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Les administrateurs peuvent modifier n'importe quel commentaire
DROP POLICY IF EXISTS "Admins can update any comment." ON comments;
CREATE POLICY "Admins can update any comment." 
  ON comments FOR UPDATE 
  USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  );

-- Les utilisateurs peuvent supprimer leurs propres commentaires OU les admins peuvent supprimer n'importe quel commentaire
DROP POLICY IF EXISTS "Users can delete own comments or admins can delete any." ON comments;
CREATE POLICY "Users can delete own comments or admins can delete any." 
  ON comments FOR DELETE 
  USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  );


-- ============================================
-- SECTION 4: FONCTIONS ET TRIGGERS
-- ============================================

-- -----------------------------------------------
-- Fonction: handle_new_user
-- Description: Crée automatiquement un profil lors de l'inscription
-- -----------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url, is_admin)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'username', 
    new.raw_user_meta_data->>'avatar_url',
    false
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- -----------------------------------------------
-- Trigger: on_auth_user_created
-- Description: Déclenche la création du profil lors de l'inscription
-- -----------------------------------------------
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ============================================
-- SECTION 5: POLITIQUES DE STOCKAGE (STORAGE)
-- ============================================
-- Note: Le bucket 'avatars' doit être créé manuellement via l'interface Supabase
-- Storage → Create bucket → Name: "avatars" → Public: Yes
-- ============================================

-- Permettre aux utilisateurs authentifiés d'uploader leur propre avatar
DROP POLICY IF EXISTS "Users can upload own avatar" ON storage.objects;
CREATE POLICY "Users can upload own avatar" 
  ON storage.objects FOR INSERT 
  TO authenticated
  WITH CHECK (
    bucket_id = 'avatars' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- Permettre aux utilisateurs authentifiés de mettre à jour leur propre avatar
DROP POLICY IF EXISTS "Users can update own avatar" ON storage.objects;
CREATE POLICY "Users can update own avatar" 
  ON storage.objects FOR UPDATE 
  TO authenticated
  USING (
    bucket_id = 'avatars' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- Permettre aux utilisateurs authentifiés de supprimer leur propre avatar
DROP POLICY IF EXISTS "Users can delete own avatar" ON storage.objects;
CREATE POLICY "Users can delete own avatar" 
  ON storage.objects FOR DELETE 
  TO authenticated
  USING (
    bucket_id = 'avatars' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- Permettre à tout le monde de voir tous les avatars
DROP POLICY IF EXISTS "Public can view avatars" ON storage.objects;
CREATE POLICY "Public can view avatars" 
  ON storage.objects FOR SELECT 
  TO public
  USING (bucket_id = 'avatars');


-- ============================================
-- SECTION 6: VÉRIFICATION ET RÉSUMÉ
-- ============================================

-- Afficher un résumé des tables créées
DO $$
BEGIN
  RAISE NOTICE '✅ Script d''initialisation terminé !';
  RAISE NOTICE '';
  RAISE NOTICE '📊 Tables créées :';
  RAISE NOTICE '   - profiles (avec colonne is_admin)';
  RAISE NOTICE '   - questions (avec is_answered, updated_at, last_editor_id)';
  RAISE NOTICE '   - comments (avec updated_at, last_editor_id)';
  RAISE NOTICE '';
  RAISE NOTICE '🔒 Row Level Security (RLS) activé sur toutes les tables';
  RAISE NOTICE '';
  RAISE NOTICE '⚙️  Fonctions et Triggers créés :';
  RAISE NOTICE '   - handle_new_user() : création automatique des profils';
  RAISE NOTICE '   - on_auth_user_created : trigger sur auth.users';
  RAISE NOTICE '';
  RAISE NOTICE '📁 Politiques de stockage configurées pour le bucket "avatars"';
  RAISE NOTICE '';
  RAISE NOTICE '⚠️  N''oubliez pas de :';
  RAISE NOTICE '   1. Créer le bucket "avatars" en mode PUBLIC via Storage';
  RAISE NOTICE '   2. Définir is_admin = true pour les administrateurs';
  RAISE NOTICE '';
  RAISE NOTICE '🚀 La base de données est prête à l''emploi !';
END $$;
